import { Form, Head, Link, router } from '@inertiajs/react';
import { CalendarClock, CreditCard, Mail, PauseCircle, PlayCircle, ShieldCheck, UsersRound } from 'lucide-react';
import { AdminPageHeader } from '@/features/admin/components/admin-page-header';
import { AdminStatusBadge } from '@/features/admin/components/admin-status-badge';
import { adminRoutes, formatAdminDate, formatAdminMoney, type AdminClient } from '@/features/admin/types';
import { PageCanvas } from '@/components/operational';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

type Props = { client: AdminClient & { phone?: string | null; notes?: string | null; subscription?: { startedAt?: string | null; renewsAt?: string | null; seats?: number; paymentMethod?: string | null } } };

export default function PlatformClientShow({ client }: Props) {
    const subscription = client.subscription ?? { startedAt: client.createdAt, renewsAt: client.renewsAt, seats: client.members, paymentMethod: 'Não informado' };
    const isSuspended = client.status === 'suspended';
    return <><Head title={client.name} /><PageCanvas className="gap-8"><AdminPageHeader title={client.name} description={client.company ?? client.email} backHref={adminRoutes.clients} actionHref={adminRoutes.clients} actionLabel="Todos os clientes" />
        <div className="flex flex-wrap items-center gap-3"><AdminStatusBadge status={client.status} /><span className="text-sm text-muted-foreground">Cliente desde {formatAdminDate(client.createdAt)}</span><div className="ml-auto flex flex-wrap gap-2"><Button variant="outline" onClick={() => router.post(`${adminRoutes.client(client.id)}/send-access`)}><Mail className="size-4" />Enviar acesso</Button><Form action={`${adminRoutes.client(client.id)}/${isSuspended ? 'activate' : 'suspend'}`} method="post"><Button variant={isSuspended ? 'default' : 'outline'} type="submit">{isSuspended ? <PlayCircle className="size-4" /> : <PauseCircle className="size-4" />}{isSuspended ? 'Reativar conta' : 'Suspender conta'}</Button></Form></div></div>
        <section className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2"><CreditCard className="size-5 text-primary" />Assinatura atual</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">Plano</p><p className="mt-1 text-lg font-semibold">{client.plan}</p><p className="text-sm text-muted-foreground">{formatAdminMoney(client.monthlyValueCents)} / mês</p></div><div><p className="text-xs text-muted-foreground">Próxima cobrança</p><p className="mt-1 text-lg font-semibold">{formatAdminDate(subscription.renewsAt)}</p><p className="text-sm text-muted-foreground">{subscription.paymentMethod}</p></div><div><p className="text-xs text-muted-foreground">Início do plano</p><p className="mt-1 font-medium">{formatAdminDate(subscription.startedAt)}</p></div><div><p className="text-xs text-muted-foreground">Assentos utilizados</p><p className="mt-1 font-medium">{client.members} de {subscription.seats ?? client.members} usuários</p></div></CardContent></Card>
        <Card><CardHeader><CardTitle>Dados de contato</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-lg bg-secondary"><Mail className="size-4" /></div><div><p className="text-xs text-muted-foreground">E-mail principal</p><p className="text-sm font-medium">{client.email}</p></div></div>{client.phone ? <div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-lg bg-secondary"><UsersRound className="size-4" /></div><div><p className="text-xs text-muted-foreground">Telefone</p><p className="text-sm font-medium">{client.phone}</p></div></div> : null}<div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-lg bg-secondary"><ShieldCheck className="size-4" /></div><div><p className="text-xs text-muted-foreground">Conta</p><p className="text-sm font-medium">Acesso administrativo habilitado</p></div></div></CardContent></Card></section>
        <Card><CardHeader><CardTitle>Atividade recente</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex items-start gap-3"><CalendarClock className="mt-0.5 size-4 text-muted-foreground" /><div><p className="text-sm">Renovação acompanhada</p><p className="text-xs text-muted-foreground">Próximo ciclo em {formatAdminDate(subscription.renewsAt)}</p></div></div><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 size-4 text-muted-foreground" /><div><p className="text-sm">Plano {client.plan} ativo</p><p className="text-xs text-muted-foreground">A equipe pode acessar todos os recursos contratados.</p></div></div></CardContent></Card>
    </PageCanvas></>;
}
PlatformClientShow.layout = { breadcrumbs: [{ title: 'Administração', href: adminRoutes.dashboard }, { title: 'Clientes', href: adminRoutes.clients }] };
